// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestComponent: typeof import('./src/components/test-component.vue')['default']
    Vue3Echarts: typeof import('./src/components/vue3-echarts/vue3-echarts.vue')['default']
    Wxs: typeof import('./src/components/wxs.vue')['default']
  }
}
